// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// processTrace_rcpp
List processTrace_rcpp(const NumericVector traceTimes, const IntegerVector traceEvents, const int alphabetLength, const List intervals, const int automaton);
RcppExport SEXP automatonR_processTrace_rcpp(SEXP traceTimesSEXP, SEXP traceEventsSEXP, SEXP alphabetLengthSEXP, SEXP intervalsSEXP, SEXP automatonSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericVector >::type traceTimes(traceTimesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type traceEvents(traceEventsSEXP);
    Rcpp::traits::input_parameter< const int >::type alphabetLength(alphabetLengthSEXP);
    Rcpp::traits::input_parameter< const List >::type intervals(intervalsSEXP);
    Rcpp::traits::input_parameter< const int >::type automaton(automatonSEXP);
    __result = Rcpp::wrap(processTrace_rcpp(traceTimes, traceEvents, alphabetLength, intervals, automaton));
    return __result;
END_RCPP
}
