# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

processTrace_rcpp <- function(traceTimes, traceEvents, alphabetLength, automaton, reClass) {
    .Call('automatonR_processTrace_rcpp', PACKAGE = 'automatonR', traceTimes, traceEvents, alphabetLength, automaton, reClass)
}

